# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamint.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreamint.proto\x12\tstreamint\"!\n\x10StreamIntRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"5\n\x11StreamIntResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\\\n\x10StreamIntService\x12H\n\tStreamInt\x12\x1b.streamint.StreamIntRequest\x1a\x1c.streamint.StreamIntResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINTREQUEST']._serialized_start=30
  _globals['_STREAMINTREQUEST']._serialized_end=63
  _globals['_STREAMINTRESPONSE']._serialized_start=65
  _globals['_STREAMINTRESPONSE']._serialized_end=118
  _globals['_STREAMINTSERVICE']._serialized_start=120
  _globals['_STREAMINTSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
